(function() {var implementors = {};
implementors["ethcore_light"] = [];implementors["ethsync"] = ["impl&lt;L:&nbsp;<a class='trait' href='ethcore_light/client/trait.LightChainClient.html' title='ethcore_light::client::LightChainClient'>LightChainClient</a>&gt; <a class='trait' href='ethcore_light/net/trait.Handler.html' title='ethcore_light::net::Handler'>Handler</a> for <a class='struct' href='ethsync/light_sync/struct.LightSync.html' title='ethsync::light_sync::LightSync'>LightSync</a>&lt;L&gt;",];implementors["ethcore_rpc"] = ["impl&lt;L&gt; <a class='trait' href='ethcore_light/net/trait.Handler.html' title='ethcore_light::net::Handler'>Handler</a> for <a class='struct' href='ethsync/light_sync/struct.LightSync.html' title='ethsync::light_sync::LightSync'>LightSync</a>&lt;L&gt; <span class='where'>where L: <a class='trait' href='ethcore_light/client/trait.LightChainClient.html' title='ethcore_light::client::LightChainClient'>LightChainClient</a></span>",];implementors["ethcore_dapps"] = ["impl&lt;L&gt; <a class='trait' href='ethcore_light/net/trait.Handler.html' title='ethcore_light::net::Handler'>Handler</a> for <a class='struct' href='ethsync/light_sync/struct.LightSync.html' title='ethsync::light_sync::LightSync'>LightSync</a>&lt;L&gt; <span class='where'>where L: <a class='trait' href='ethcore_light/client/trait.LightChainClient.html' title='ethcore_light::client::LightChainClient'>LightChainClient</a></span>",];implementors["parity"] = ["impl&lt;L&gt; <a class='trait' href='ethcore_light/net/trait.Handler.html' title='ethcore_light::net::Handler'>Handler</a> for <a class='struct' href='ethsync/light_sync/struct.LightSync.html' title='ethsync::light_sync::LightSync'>LightSync</a>&lt;L&gt; <span class='where'>where L: <a class='trait' href='ethcore_light/client/trait.LightChainClient.html' title='ethcore_light::client::LightChainClient'>LightChainClient</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
